---
- name: Create and start services
  become: true
  community.docker.docker_compose_v2:
    project_src: "docker-compose.yml"
    project_name: {{ project_dir }}
  register: compose_output

- name: Show results
  debug:
    var: compose_output.results

