
services:
  portainer-ce:
    container_name: portainer
    restart: always
    ports:
      - '8000:8000'
      - '9000:9000'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './portainer_data:/data'
    image: portainer/portainer-ce

  guacamole:
    container_name: guacamole
    restart: unless-stopped
    image: jwetzell/guacamole
    volumes:
      - ./postgres:/config
    ports:
      - '8080:8080'

volumes:
  postgres:
    driver: local

networks:
  default:
    name: my-main-net

