- name: Install and configure i3 window manager
  hosts: home_machines
  become: yes
  vars_files:
    - vault.yml
  vars:
    user_home: "/home/{{ inventory_hostname }}"
    config_src: "/home/exa/env/nixconfig/dotfiles/"
    config_dest: "{{ user_home }}/.config/"

  tasks:
    - name: Install i3 and necessary packages
      package:
        become: true
        name: "{{ item }}"
        state: present
      loop:
        - i3
        - i3status
        - i3lock
        - rofi
        - feh
        - picom
        - dunst
        - vifm 
    - name: Copy configuration files
      copy:
        src: "{{ dotf }}/{{ item }}"
        dest: "{{ user_home }}/{{ item }}"
        owner: "{{ inventory_hostname }}"
        group: "{{ inventory_hostname }}"
        mode: '0644'
        backup: false
        force: true

      loop:
        - i3 
        - dunst
        - picom
        - vifm 

 
