---
- name: Setup the environment from the Git repo
  hosts: test
  vars_files:
    - ../vault.yml
  vars:
    user_home: "/home/{{ inventory_hostname }}"
    git_repo: "{{ user_home }}/Desktop/nixconfig"
    dotfiles: "{{ git_repo }}/dotfiles"
    

  tasks:
    - name: Clone backup branch
      git:
        repo: https://github.com/DnFreddie/nixconfig.git
        dest: "{{ git_repo }}"
        single_branch: yes
        version: backup

    - name: Include and pass variables to the other playbook
      include_tasks: terminal.yml

