- name: Install i3 and necessary packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
    - i3
    - i3status
    - i3lock
    - rofi
    - feh
    - picom
    - dunst
    - vifm 
- name: Copy configuration files
  copy:
    remote_src: true
    src: "{{ dotfiles }}/{{ item }}"
    dest: "{{ config_dest }}"
    owner: "{{ inventory_hostname }}"
    group: "{{ inventory_hostname }}"
    mode: '0755'
    backup: false
    force: true

  loop:
    - i3 
    - dunst
    - picom
    - vifm 


