- name: Install the nix and intall requaierd flake pacages
  hosts: proxy
  become: true
  vars_files:
    - vault.yml

  tasks:
    - name: Ensure /etc/nix directory exists
      ansible.builtin.file:
        path: /etc/nix
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Copy tool.nix file to /etc/nix/
      ansible.builtin.copy:
        src: ./{{ item }}
        dest: /etc/nix/{{ item}}
        owner: root
        backup: false
        force: true
        group: root
        mode: '0664'
      loop:
        - flake.nix
        - tools.nix

    - name: Append line to tool.nix file
      ansible.builtin.lineinfile:
        path: /etc/nix/nix.conf
        line: "experimental-features = nix-command flakes"
        create: true
        mode: '0664'

    - name: Install nix 
      become: true
      vars_files:
        - vault.yml
      roles:
        - role: danielrolls.nix
          vars:
            nix_commands:
              - " nix run /etc/nix/ "

